[package]
name = "mdns-responder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmdns = "0.6"
clap = "2"
env_logger = "0.9.0"
